pipeline {
    agent any

    tools {
        jdk 'JAVA_HOME'
        maven 'M2_HOME'
    }

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        
        stage('Git') {
            steps {
                git branch: 'idriss_ben_younes', changelog: false, poll: false, url: 'https://github.com/CAPDEV-ORG/DevOps-ProjectFoyer.git'
            }
        }

        stage('Testing mvn') {
            steps {
                sh 'mvn -version'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Display Date') {
            steps {
                script {
                    def currentDate = new Date()
                    echo "Current Date: ${currentDate}"
                }
            }
        }
    }

 post {
     success {
         emailext(
             subject: "SUCCESS: Build #${currentBuild.number} - ${currentBuild.fullDisplayName}",
             body: """
                 <h2>Build Successful!</h2>
                 <p>The build was successful!</p>
                 <p>Check it out here: <a href="${env.BUILD_URL}">${env.BUILD_URL}</a></p>
                 <p>Commit: <strong>${env.GIT_COMMIT}</strong></p>
                 <p>Branch: <strong>${env.GIT_BRANCH}</strong></p>
                 <p>Triggered by: ${currentBuild.triggeredBy}</p>
             """,
             to: 'idross.benyounes208@gmail.com',
             mimeType: 'text/html' // Send the email as HTML for better formatting
         )
     }
     unstable {
         emailext(
             subject: "UNSTABLE: Build #${currentBuild.number} - ${currentBuild.fullDisplayName}",
             body: """
                 <h2>Build Unstable!</h2>
                 <p>The build is unstable.</p>
                 <p>Check the details here: <a href="${env.BUILD_URL}">${env.BUILD_URL}</a></p>
                 <p>Commit: <strong>${env.GIT_COMMIT}</strong></p>
                 <p>Branch: <strong>${env.GIT_BRANCH}</strong></p>
                 <p>Triggered by: ${currentBuild.triggeredBy}</p>
             """,
             to: 'idross.benyounes208@gmail.com',
             mimeType: 'text/html'
         )
     }
     failure {
         emailext(
             subject: "FAILED: Build #${currentBuild.number} - ${currentBuild.fullDisplayName}",
             body: """
                 <h2>Build Failed!</h2>
                 <p>The build has failed.</p>
                 <p>Check the logs here: <a href="${env.BUILD_URL}">${env.BUILD_URL}</a></p>
                 <p>Commit: <strong>${env.GIT_COMMIT}</strong></p>
                 <p>Branch: <strong>${env.GIT_BRANCH}</strong></p>
                 <p>Triggered by: ${currentBuild.triggeredBy}</p>
             """,
             to: 'idross.benyounes208@gmail.com',
             mimeType: 'text/html'
         )
     }
 }


}
