pipeline {
    agent any

    tools {
        jdk 'JAVA_HOME'
        maven 'M2_HOME'
    }

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        
        stage('Git') {
            steps {
                git branch: 'idriss_ben_younes', changelog: false, poll: false, url: 'https://github.com/CAPDEV-ORG/DevOps-ProjectFoyer.git'
            }
        }

        stage('Testing mvn') {
            steps {
                sh 'mvn -version'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Display Date') {
            steps {
                script {
                    def currentDate = new Date()
                    echo "Current Date: ${currentDate}"
                }
            }
        }
    }

    post {
        success {
            script {
                emailext(
                    subject: "SUCCESS: Build ${currentBuild.fullDisplayName}",
                    body: "The  build was successful\n\nCheck it out here: ${env.BUILD_URL}",
                    to: 'idross.benyounes208@gmail.com'
                )
            }
        }
        unstable {
            script {
                emailext(
                    subject: "UNSTABLE: Build ${currentBuild.fullDisplayName}",
                    body: "The build is unstable.\n\nCheck the details here: ${env.BUILD_URL}",
                    to: 'idross.benyounes208@gmail.com'
                )
            }
        }
        failure {
            script {
                emailext(
                    subject: "FAILED: Build ${currentBuild.fullDisplayName}",
                    body: "The build has failed.\n\nCheck the logs here: ${env.BUILD_URL}",
                    to: 'idross.benyounes208@gmail.com'
                )
            }
        }
    }
}
